### ISSUE TITLE
Add remove-gutter utility class

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/hawkeye#1]
A utility class that can be implemented to override container or col padding would be helpful. 

```scss
.remove-gutter {
  margin-left: -($grid-gutter-width / 2);
  margin-right: -($grid-gutter-width / 2);
}
```
